### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by xuwillie** [ije/jex.me#2]
Hayyy, your website that amazing me!

I want to know how your journal page made?
I want to  build blog with MarkDown support, how can I set up?

**Comment by ije** [comment]
thanks, this site was built a long time ago...with JavaScript and Golang(backend)
you may have interesting in [Aleph.js](https://githbu.com/alephjs/aleph.js), now i am rewriting it, also i am updating the docs with markdown: https://github.com/alephjs/alephjs.org/pull/58
